"use strict";
let lname;
lname = "Gabriel";
let newname = lname.toUpperCase();
console.log(newname);
let age;
age = 25;
age = 25.5;
let dob = "25";
let result = parseInt(dob);
let isValid = false;
console.log(isValid);
let empList;
empList = ["Gabriel", "Gabriel", "Gabriel",];
let numList;
numList = [1, 2, 3, 4];
let results = numList.filter((num) => num > 2);
let num = numList.find((num) => num === 2);
console.log(results);
console.log(num);
